# Generated by Django 4.2.30 on 2026-07-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
