# Generated by Django 4.2.30 on 2026-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE_RETURN', 'Sale Return')], max_length=20),
        ),
    ]
