# Generated by Django 4.2.30 on 2026-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='subtotal',
        ),
    ]
