# Generated by Django 4.2.30 on 2026-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
