# Generated by Django 4.2.30 on 2026-07-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Sequence',
                'verbose_name_plural': 'Document Sequences',
                'ordering': ['code'],
            },
        ),
    ]
