# Generated by Django 4.2.30 on 2026-07-16 23:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_index=True, editable=False)),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('journal_type', models.CharField(choices=[('GENERAL', 'General'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CASH_RECEIPT', 'Cash Receipt'), ('CASH_PAYMENT', 'Cash Payment'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-sequence'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
