# Generated by Django 4.2.30 on 2026-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accounting_audit_and_posting_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CASH_RECEIPT', 'Cash Receipt'), ('CASH_PAYMENT', 'Cash Payment'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense'), ('PAYMENT', 'Payment'), ('CLOSING', 'Closing')], max_length=30),
        ),
    ]
