# Generated by Django 4.2.30 on 2026-07-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_journalline'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0), models.Q(('debit', 0), ('credit', 0), _connector='OR')), name='valid_debit_credit'),
        ),
    ]
