# Generated by Django 4.2.30 on 2026-08-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_journalentry_journal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='supplier',
        ),
    ]
