# Generated by Django 4.2.30 on 2026-07-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expensecategory_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CASH_RECEIPT', 'Cash Receipt'), ('CASH_PAYMENT', 'Cash Payment'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense')], max_length=30),
        ),
    ]
