# Generated by Django 4.2.30 on 2026-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_flow_category',
            field=models.CharField(choices=[('OPERATING', 'Operating Activities'), ('INVESTING', 'Investing Activities'), ('FINANCING', 'Financing Activities'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CASH_RECEIPT', 'Cash Receipt'), ('CASH_PAYMENT', 'Cash Payment'), ('ADJUSTMENT', 'Adjustment'), ('EXPENSE', 'Expense'), ('PAYMENT', 'Payment')], max_length=30),
        ),
    ]
