# Generated by Django 4.2.30 on 2026-08-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePriceHistory',
        ),
    ]
