# Generated by Django 4.2.30 on 2026-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ERP POS', max_length=255)),
                ('base_currency', models.CharField(choices=[('USD', 'USD'), ('LBP', 'LBP')], default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=90000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
