# Generated by Django 4.2.30 on 2026-07-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
    ]
