# Generated by Django 4.2.30 on 2026-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_systemsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
