# Generated by Django 4.2.30 on 2026-06-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reports', 'Can view reports')],
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
